DELETE http://localhost:3001/api/logout
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2V0eXNvbjIyMzFAZXhhbXBsZS5jb20iLCJpZCI6NCwiaWF0IjoxNjc5OTM1NjA4fQ.EN8kOwYeaq49WDZ5OFtfUfW5qQn_5n1ZpYkxSCITgKk