services:
  bloglist-frontend:
    container_name: blog-front
    build:
      context: ./bloglist-frontend/
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-frontend:/usr/src/app
    ports:
      - 3000:3000
  
  bloglist-backend:
    container_name: blog-back
    build:
      context: ./bloglist-backend/
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-backend:/usr/src/app
    ports:
      - 3003:3003
    
  mongo:
    image: mongo
    container_name: mongo-blog
    env_file:
      - ./bloglist-backend/.env
      - ./bloglist-frontend/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:       
      - ./bloglist-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./bloglist-backend/mongo_data:/data/db
    ports:
      - ${MONGODB_PORT}:27017
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-blog
    depends_on:
      - bloglist-front
      - bloglist-back